// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyGenerationDbContext))]
    [Migration("20211104150122_UpdateImageToEnergyGenerations")]
    partial class UpdateImageToEnergyGenerations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyGeneration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 1910.1m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 120.6m,
                            OtherBioEnergy = 468.9m,
                            Price = 48.04m,
                            Region = "Scotland",
                            SolarPv = 1678.3m,
                            Total = 135.5m,
                            WaveAndTidal = 753.1m,
                            Wind2 = 1880.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 1938.9m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1558.2m,
                            OtherBioEnergy = 952.6m,
                            Price = 23.75m,
                            Region = "Northern Ireland",
                            SolarPv = 124.1m,
                            Total = 1892.7m,
                            WaveAndTidal = 1726.3m,
                            Wind2 = 230.2m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 1684.0m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1530.3m,
                            OtherBioEnergy = 386.1m,
                            Price = 71.42m,
                            Region = "Scotland",
                            SolarPv = 112.6m,
                            Total = 1448.9m,
                            WaveAndTidal = 1869.7m,
                            Wind2 = 1934.6m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 1490.3m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1360.5m,
                            OtherBioEnergy = 531.7m,
                            Price = 187.91m,
                            Region = "Scotland",
                            SolarPv = 748.0m,
                            Total = 1423.0m,
                            WaveAndTidal = 995.4m,
                            Wind2 = 547.3m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 5,
                            Hydro = 936.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1178.4m,
                            OtherBioEnergy = 694.6m,
                            Price = 195.20m,
                            Region = "Scotland",
                            SolarPv = 482.1m,
                            Total = 1649.7m,
                            WaveAndTidal = 316.3m,
                            Wind2 = 1141.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Hydro = 415.1m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1832.8m,
                            OtherBioEnergy = 10.5m,
                            Price = 149.65m,
                            Region = "Scotland",
                            SolarPv = 1923.5m,
                            Total = 640.4m,
                            WaveAndTidal = 853.7m,
                            Wind2 = 393.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 7,
                            Hydro = 385.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 49.7m,
                            OtherBioEnergy = 1234.7m,
                            Price = 199.43m,
                            Region = "Scotland",
                            SolarPv = 740.7m,
                            Total = 978.2m,
                            WaveAndTidal = 256.4m,
                            Wind2 = 1019.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 8,
                            Hydro = 938.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 499.6m,
                            OtherBioEnergy = 1618.2m,
                            Price = 63.37m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 261.5m,
                            Total = 1387.6m,
                            WaveAndTidal = 1940.7m,
                            Wind2 = 1529.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 9,
                            Hydro = 1952.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1140.4m,
                            OtherBioEnergy = 1693.5m,
                            Price = 117.58m,
                            Region = "Northern Ireland",
                            SolarPv = 563.3m,
                            Total = 1071.8m,
                            WaveAndTidal = 1952.4m,
                            Wind2 = 736.4m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 10,
                            Hydro = 718.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 598.6m,
                            OtherBioEnergy = 885.2m,
                            Price = 33.29m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1572.2m,
                            Total = 1575.5m,
                            WaveAndTidal = 1428.7m,
                            Wind2 = 1891.2m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 11,
                            Hydro = 289.3m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 14.7m,
                            OtherBioEnergy = 453.0m,
                            Price = 9.66m,
                            Region = "Scotland",
                            SolarPv = 918.1m,
                            Total = 592.2m,
                            WaveAndTidal = 1016.0m,
                            Wind2 = 1716.3m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 12,
                            Hydro = 1544.1m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 998.0m,
                            OtherBioEnergy = 1067.5m,
                            Price = 98.53m,
                            Region = "England",
                            SolarPv = 1488.8m,
                            Total = 1693.0m,
                            WaveAndTidal = 1464.6m,
                            Wind2 = 622.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 13,
                            Hydro = 1228.3m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1135.3m,
                            OtherBioEnergy = 100.8m,
                            Price = 78.82m,
                            Region = "England",
                            SolarPv = 976.1m,
                            Total = 368.5m,
                            WaveAndTidal = 645.3m,
                            Wind2 = 162.9m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 14,
                            Hydro = 561.8m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1119.3m,
                            OtherBioEnergy = 1720.3m,
                            Price = 154.33m,
                            Region = "Scotland",
                            SolarPv = 288.8m,
                            Total = 1034.2m,
                            WaveAndTidal = 1290.9m,
                            Wind2 = 42.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 15,
                            Hydro = 1442.9m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 727.1m,
                            OtherBioEnergy = 426.5m,
                            Price = 27.40m,
                            Region = "Northern Ireland",
                            SolarPv = 417.4m,
                            Total = 1939.8m,
                            WaveAndTidal = 86.5m,
                            Wind2 = 1101.2m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 16,
                            Hydro = 530.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1780.7m,
                            OtherBioEnergy = 1071.0m,
                            Price = 2.80m,
                            Region = "Scotland",
                            SolarPv = 851.6m,
                            Total = 39.8m,
                            WaveAndTidal = 787.2m,
                            Wind2 = 1192.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 17,
                            Hydro = 301.1m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 171.7m,
                            OtherBioEnergy = 1331.9m,
                            Price = 168.97m,
                            Region = "Scotland",
                            SolarPv = 645.7m,
                            Total = 1175.8m,
                            WaveAndTidal = 1048.9m,
                            Wind2 = 84.5m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 18,
                            Hydro = 557.5m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1254.9m,
                            OtherBioEnergy = 76.3m,
                            Price = 92.69m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 850.5m,
                            Total = 227.8m,
                            WaveAndTidal = 1419.0m,
                            Wind2 = 33.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 19,
                            Hydro = 808.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 422.3m,
                            OtherBioEnergy = 1255.5m,
                            Price = 153.32m,
                            Region = "Northern Ireland",
                            SolarPv = 1823.1m,
                            Total = 439.2m,
                            WaveAndTidal = 340.4m,
                            Wind2 = 160.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 20,
                            Hydro = 23.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 602.9m,
                            OtherBioEnergy = 52.3m,
                            Price = 175.80m,
                            Region = "England",
                            SolarPv = 1120.0m,
                            Total = 1440.7m,
                            WaveAndTidal = 1344.5m,
                            Wind2 = 1680.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 21,
                            Hydro = 442.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1497.8m,
                            OtherBioEnergy = 1773.0m,
                            Price = 11.63m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1603.2m,
                            Total = 1936.6m,
                            WaveAndTidal = 1012.8m,
                            Wind2 = 1250.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 22,
                            Hydro = 445.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1752.9m,
                            OtherBioEnergy = 1744.0m,
                            Price = 29.41m,
                            Region = "Scotland",
                            SolarPv = 1188.5m,
                            Total = 1225.7m,
                            WaveAndTidal = 506.6m,
                            Wind2 = 843.1m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 23,
                            Hydro = 376.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1597.1m,
                            OtherBioEnergy = 688.7m,
                            Price = 183.73m,
                            Region = "Northern Ireland",
                            SolarPv = 145.9m,
                            Total = 299.0m,
                            WaveAndTidal = 1417.7m,
                            Wind2 = 892.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 24,
                            Hydro = 1106.0m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1457.9m,
                            OtherBioEnergy = 1148.0m,
                            Price = 82.67m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 262.0m,
                            Total = 737.1m,
                            WaveAndTidal = 111.4m,
                            Wind2 = 635.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 25,
                            Hydro = 1076.6m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1205.1m,
                            OtherBioEnergy = 1173.8m,
                            Price = 138.07m,
                            Region = "Northern Ireland",
                            SolarPv = 482.2m,
                            Total = 156.0m,
                            WaveAndTidal = 145.1m,
                            Wind2 = 1318.8m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 26,
                            Hydro = 354.9m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 502.5m,
                            OtherBioEnergy = 1833.0m,
                            Price = 67.48m,
                            Region = "Northern Ireland",
                            SolarPv = 237.5m,
                            Total = 866.9m,
                            WaveAndTidal = 1603.3m,
                            Wind2 = 826.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Hydro = 73.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1068.7m,
                            OtherBioEnergy = 731.6m,
                            Price = 122.68m,
                            Region = "Northern Ireland",
                            SolarPv = 339.5m,
                            Total = 244.6m,
                            WaveAndTidal = 1109.8m,
                            Wind2 = 1473.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 28,
                            Hydro = 1229.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1597.4m,
                            OtherBioEnergy = 747.4m,
                            Price = 8.24m,
                            Region = "Northern Ireland",
                            SolarPv = 526.6m,
                            Total = 935.4m,
                            WaveAndTidal = 1845.0m,
                            Wind2 = 1006.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 29,
                            Hydro = 1095.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 375.9m,
                            OtherBioEnergy = 1032.2m,
                            Price = 106.92m,
                            Region = "England",
                            SolarPv = 555.9m,
                            Total = 1873.9m,
                            WaveAndTidal = 1624.2m,
                            Wind2 = 532.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 30,
                            Hydro = 501.5m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1175.3m,
                            OtherBioEnergy = 208.9m,
                            Price = 190.71m,
                            Region = "Scotland",
                            SolarPv = 535.4m,
                            Total = 1805.6m,
                            WaveAndTidal = 1510.3m,
                            Wind2 = 281.0m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 31,
                            Hydro = 1665.8m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1852.0m,
                            OtherBioEnergy = 981.6m,
                            Price = 40.90m,
                            Region = "England",
                            SolarPv = 1687.5m,
                            Total = 1076.6m,
                            WaveAndTidal = 73.5m,
                            Wind2 = 929.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 32,
                            Hydro = 421.9m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 276.2m,
                            OtherBioEnergy = 1849.6m,
                            Price = 100.80m,
                            Region = "Scotland",
                            SolarPv = 55.6m,
                            Total = 553.9m,
                            WaveAndTidal = 1797.7m,
                            Wind2 = 897.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 33,
                            Hydro = 1362.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 323.8m,
                            OtherBioEnergy = 1496.5m,
                            Price = 124.37m,
                            Region = "England",
                            SolarPv = 1479.0m,
                            Total = 1309.5m,
                            WaveAndTidal = 337.4m,
                            Wind2 = 857.7m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 34,
                            Hydro = 697.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1494.0m,
                            OtherBioEnergy = 459.2m,
                            Price = 2.50m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1061.3m,
                            Total = 1936.7m,
                            WaveAndTidal = 526.4m,
                            Wind2 = 941.8m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 35,
                            Hydro = 848.3m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 727.3m,
                            OtherBioEnergy = 483.3m,
                            Price = 89.01m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1149.6m,
                            Total = 1454.7m,
                            WaveAndTidal = 865.8m,
                            Wind2 = 1955.5m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 36,
                            Hydro = 1971.5m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1615.8m,
                            OtherBioEnergy = 591.7m,
                            Price = 11.35m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 711.7m,
                            Total = 594.5m,
                            WaveAndTidal = 561.8m,
                            Wind2 = 1655.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 37,
                            Hydro = 1369.0m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 813.2m,
                            OtherBioEnergy = 371.1m,
                            Price = 32.52m,
                            Region = "England",
                            SolarPv = 953.9m,
                            Total = 736.4m,
                            WaveAndTidal = 1051.6m,
                            Wind2 = 1672.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 38,
                            Hydro = 303.0m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 80.8m,
                            OtherBioEnergy = 1991.8m,
                            Price = 135.79m,
                            Region = "Scotland",
                            SolarPv = 0.0m,
                            Total = 1187.8m,
                            WaveAndTidal = 1663.8m,
                            Wind2 = 1912.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 39,
                            Hydro = 728.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1733.4m,
                            OtherBioEnergy = 379.9m,
                            Price = 63.06m,
                            Region = "Scotland",
                            SolarPv = 1799.7m,
                            Total = 1814.6m,
                            WaveAndTidal = 1195.9m,
                            Wind2 = 41.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 40,
                            Hydro = 888.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1722.2m,
                            OtherBioEnergy = 903.9m,
                            Price = 108.98m,
                            Region = "Northern Ireland",
                            SolarPv = 1548.0m,
                            Total = 1911.9m,
                            WaveAndTidal = 1611.4m,
                            Wind2 = 1864.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 41,
                            Hydro = 408.2m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1412.7m,
                            OtherBioEnergy = 1991.2m,
                            Price = 178.05m,
                            Region = "England",
                            SolarPv = 1185.7m,
                            Total = 561.8m,
                            WaveAndTidal = 96.7m,
                            Wind2 = 1746.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 42,
                            Hydro = 1501.5m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 313.6m,
                            OtherBioEnergy = 476.0m,
                            Price = 40.87m,
                            Region = "Scotland",
                            SolarPv = 1690.3m,
                            Total = 1251.8m,
                            WaveAndTidal = 1963.8m,
                            Wind2 = 1403.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 43,
                            Hydro = 25.5m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1952.4m,
                            OtherBioEnergy = 301.5m,
                            Price = 22.55m,
                            Region = "England",
                            SolarPv = 276.0m,
                            Total = 115.7m,
                            WaveAndTidal = 1646.6m,
                            Wind2 = 556.4m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 44,
                            Hydro = 278.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 93.4m,
                            OtherBioEnergy = 1945.0m,
                            Price = 111.17m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 595.5m,
                            Total = 10.2m,
                            WaveAndTidal = 1407.2m,
                            Wind2 = 79.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 45,
                            Hydro = 1457.9m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1498.4m,
                            OtherBioEnergy = 1900.7m,
                            Price = 139.15m,
                            Region = "Scotland",
                            SolarPv = 1199.1m,
                            Total = 1921.0m,
                            WaveAndTidal = 1405.9m,
                            Wind2 = 1818.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 46,
                            Hydro = 1601.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1799.6m,
                            OtherBioEnergy = 100.3m,
                            Price = 4.65m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 144.9m,
                            Total = 1820.7m,
                            WaveAndTidal = 1686.3m,
                            Wind2 = 1652.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 47,
                            Hydro = 713.7m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1544.0m,
                            OtherBioEnergy = 1996.6m,
                            Price = 116.02m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1827.9m,
                            Total = 1368.3m,
                            WaveAndTidal = 1450.1m,
                            Wind2 = 1875.5m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 48,
                            Hydro = 1893.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 615.2m,
                            OtherBioEnergy = 1150.5m,
                            Price = 141.16m,
                            Region = "England",
                            SolarPv = 909.8m,
                            Total = 447.4m,
                            WaveAndTidal = 1860.2m,
                            Wind2 = 465.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 49,
                            Hydro = 1334.6m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1524.6m,
                            OtherBioEnergy = 393.5m,
                            Price = 81.80m,
                            Region = "England",
                            SolarPv = 537.1m,
                            Total = 1262.3m,
                            WaveAndTidal = 69.2m,
                            Wind2 = 380.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 50,
                            Hydro = 204.4m,
                            Image = "https://4d1e-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1866.6m,
                            OtherBioEnergy = 367.9m,
                            Price = 99.37m,
                            Region = "Scotland",
                            SolarPv = 935.7m,
                            Total = 1578.0m,
                            WaveAndTidal = 850.0m,
                            Wind2 = 124.2m,
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
