// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyGenerationDbContext))]
    [Migration("20211104160238_UpdateImageToEnergyGenerations2")]
    partial class UpdateImageToEnergyGenerations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyGeneration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 319.8m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 799.5m,
                            OtherBioEnergy = 201.7m,
                            Price = 197.70m,
                            Region = "England",
                            SolarPv = 360.9m,
                            Total = 1055.2m,
                            WaveAndTidal = 271.9m,
                            Wind2 = 607.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 982.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 578.4m,
                            OtherBioEnergy = 1023.2m,
                            Price = 57.57m,
                            Region = "Scotland",
                            SolarPv = 1654.0m,
                            Total = 1339.2m,
                            WaveAndTidal = 1435.8m,
                            Wind2 = 1502.3m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 776.8m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1588.8m,
                            OtherBioEnergy = 852.1m,
                            Price = 176.94m,
                            Region = "Northern Ireland",
                            SolarPv = 921.2m,
                            Total = 1692.5m,
                            WaveAndTidal = 1215.4m,
                            Wind2 = 1630.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 1514.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1715.4m,
                            OtherBioEnergy = 1937.6m,
                            Price = 171.05m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1217.0m,
                            Total = 967.1m,
                            WaveAndTidal = 640.0m,
                            Wind2 = 1177.3m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 5,
                            Hydro = 163.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1694.8m,
                            OtherBioEnergy = 1254.4m,
                            Price = 56.74m,
                            Region = "England",
                            SolarPv = 947.3m,
                            Total = 496.5m,
                            WaveAndTidal = 129.9m,
                            Wind2 = 1813.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Hydro = 557.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 478.7m,
                            OtherBioEnergy = 1392.2m,
                            Price = 11.12m,
                            Region = "Scotland",
                            SolarPv = 58.3m,
                            Total = 1350.7m,
                            WaveAndTidal = 588.5m,
                            Wind2 = 1868.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 7,
                            Hydro = 278.7m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 620.7m,
                            OtherBioEnergy = 862.2m,
                            Price = 158.40m,
                            Region = "Scotland",
                            SolarPv = 1756.4m,
                            Total = 218.8m,
                            WaveAndTidal = 1344.7m,
                            Wind2 = 509.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 8,
                            Hydro = 1914.8m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 809.0m,
                            OtherBioEnergy = 1500.6m,
                            Price = 13.90m,
                            Region = "Northern Ireland",
                            SolarPv = 1436.0m,
                            Total = 268.1m,
                            WaveAndTidal = 771.8m,
                            Wind2 = 56.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 9,
                            Hydro = 1292.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1377.1m,
                            OtherBioEnergy = 588.8m,
                            Price = 75.81m,
                            Region = "England",
                            SolarPv = 618.0m,
                            Total = 581.7m,
                            WaveAndTidal = 1581.3m,
                            Wind2 = 355.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 10,
                            Hydro = 385.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1494.5m,
                            OtherBioEnergy = 469.2m,
                            Price = 65.97m,
                            Region = "England",
                            SolarPv = 1836.4m,
                            Total = 373.5m,
                            WaveAndTidal = 1383.1m,
                            Wind2 = 586.8m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 11,
                            Hydro = 451.7m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1470.3m,
                            OtherBioEnergy = 1096.6m,
                            Price = 66.86m,
                            Region = "Northern Ireland",
                            SolarPv = 844.5m,
                            Total = 1152.4m,
                            WaveAndTidal = 357.4m,
                            Wind2 = 1035.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 12,
                            Hydro = 396.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1591.7m,
                            OtherBioEnergy = 927.9m,
                            Price = 14.35m,
                            Region = "Northern Ireland",
                            SolarPv = 502.0m,
                            Total = 726.6m,
                            WaveAndTidal = 592.5m,
                            Wind2 = 1124.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 13,
                            Hydro = 943.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 53.9m,
                            OtherBioEnergy = 672.9m,
                            Price = 46.35m,
                            Region = "England",
                            SolarPv = 1102.8m,
                            Total = 935.3m,
                            WaveAndTidal = 1559.0m,
                            Wind2 = 280.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 14,
                            Hydro = 249.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1298.7m,
                            OtherBioEnergy = 1998.2m,
                            Price = 105.00m,
                            Region = "England",
                            SolarPv = 1215.8m,
                            Total = 736.7m,
                            WaveAndTidal = 1599.5m,
                            Wind2 = 1127.1m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 15,
                            Hydro = 58.1m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1199.1m,
                            OtherBioEnergy = 1994.3m,
                            Price = 16.62m,
                            Region = "England",
                            SolarPv = 911.6m,
                            Total = 881.0m,
                            WaveAndTidal = 438.1m,
                            Wind2 = 1436.3m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 16,
                            Hydro = 1510.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 552.0m,
                            OtherBioEnergy = 1476.6m,
                            Price = 143.98m,
                            Region = "Northern Ireland",
                            SolarPv = 1767.0m,
                            Total = 1254.5m,
                            WaveAndTidal = 1909.9m,
                            Wind2 = 1742.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 17,
                            Hydro = 1408.3m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1850.8m,
                            OtherBioEnergy = 1524.5m,
                            Price = 190.11m,
                            Region = "Northern Ireland",
                            SolarPv = 1723.3m,
                            Total = 1376.7m,
                            WaveAndTidal = 102.3m,
                            Wind2 = 161.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 18,
                            Hydro = 620.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 595.4m,
                            OtherBioEnergy = 1842.3m,
                            Price = 25.26m,
                            Region = "Scotland",
                            SolarPv = 641.0m,
                            Total = 647.3m,
                            WaveAndTidal = 560.4m,
                            Wind2 = 191.1m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 19,
                            Hydro = 1853.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 597.2m,
                            OtherBioEnergy = 1217.2m,
                            Price = 104.47m,
                            Region = "England",
                            SolarPv = 255.8m,
                            Total = 1832.4m,
                            WaveAndTidal = 1495.5m,
                            Wind2 = 1791.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 20,
                            Hydro = 1025.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 119.2m,
                            OtherBioEnergy = 1334.0m,
                            Price = 170.53m,
                            Region = "Scotland",
                            SolarPv = 1768.4m,
                            Total = 714.8m,
                            WaveAndTidal = 835.6m,
                            Wind2 = 743.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 21,
                            Hydro = 1200.7m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 375.4m,
                            OtherBioEnergy = 1182.1m,
                            Price = 150.32m,
                            Region = "Scotland",
                            SolarPv = 342.0m,
                            Total = 1268.9m,
                            WaveAndTidal = 628.3m,
                            Wind2 = 617.5m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 22,
                            Hydro = 338.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1005.6m,
                            OtherBioEnergy = 665.7m,
                            Price = 114.60m,
                            Region = "Northern Ireland",
                            SolarPv = 156.7m,
                            Total = 1846.5m,
                            WaveAndTidal = 209.8m,
                            Wind2 = 829.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 23,
                            Hydro = 1275.6m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 849.8m,
                            OtherBioEnergy = 1355.5m,
                            Price = 186.97m,
                            Region = "Northern Ireland",
                            SolarPv = 555.2m,
                            Total = 792.0m,
                            WaveAndTidal = 1671.3m,
                            Wind2 = 1692.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 24,
                            Hydro = 69.8m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1442.0m,
                            OtherBioEnergy = 1163.4m,
                            Price = 161.59m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 837.4m,
                            Total = 1153.4m,
                            WaveAndTidal = 1144.1m,
                            Wind2 = 1127.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 25,
                            Hydro = 987.7m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 992.9m,
                            OtherBioEnergy = 533.8m,
                            Price = 105.50m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 790.3m,
                            Total = 678.8m,
                            WaveAndTidal = 686.3m,
                            Wind2 = 1948.3m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 26,
                            Hydro = 1573.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1982.3m,
                            OtherBioEnergy = 946.2m,
                            Price = 143.02m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 692.0m,
                            Total = 73.1m,
                            WaveAndTidal = 845.1m,
                            Wind2 = 1487.4m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Hydro = 1653.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1582.0m,
                            OtherBioEnergy = 1685.1m,
                            Price = 106.64m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 644.3m,
                            Total = 1372.4m,
                            WaveAndTidal = 1652.9m,
                            Wind2 = 390.1m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 28,
                            Hydro = 1396.1m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 685.3m,
                            OtherBioEnergy = 1005.8m,
                            Price = 8.69m,
                            Region = "Scotland",
                            SolarPv = 391.5m,
                            Total = 881.0m,
                            WaveAndTidal = 791.4m,
                            Wind2 = 1512.3m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 29,
                            Hydro = 1048.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1773.9m,
                            OtherBioEnergy = 282.4m,
                            Price = 156.74m,
                            Region = "England",
                            SolarPv = 1596.5m,
                            Total = 452.0m,
                            WaveAndTidal = 1361.7m,
                            Wind2 = 676.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 30,
                            Hydro = 458.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1024.9m,
                            OtherBioEnergy = 295.4m,
                            Price = 126.38m,
                            Region = "England",
                            SolarPv = 704.1m,
                            Total = 41.9m,
                            WaveAndTidal = 87.0m,
                            Wind2 = 1090.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 31,
                            Hydro = 177.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1941.1m,
                            OtherBioEnergy = 696.0m,
                            Price = 113.67m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 534.0m,
                            Total = 453.5m,
                            WaveAndTidal = 591.9m,
                            Wind2 = 1161.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 32,
                            Hydro = 34.8m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 343.2m,
                            OtherBioEnergy = 1028.3m,
                            Price = 129.59m,
                            Region = "Northern Ireland",
                            SolarPv = 783.7m,
                            Total = 56.3m,
                            WaveAndTidal = 505.7m,
                            Wind2 = 65.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 33,
                            Hydro = 400.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 751.8m,
                            OtherBioEnergy = 1425.2m,
                            Price = 159.60m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1999.4m,
                            Total = 87.2m,
                            WaveAndTidal = 108.5m,
                            Wind2 = 1233.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 34,
                            Hydro = 974.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1154.6m,
                            OtherBioEnergy = 84.7m,
                            Price = 193.33m,
                            Region = "England",
                            SolarPv = 161.7m,
                            Total = 827.7m,
                            WaveAndTidal = 1744.2m,
                            Wind2 = 963.8m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 35,
                            Hydro = 1110.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 430.6m,
                            OtherBioEnergy = 584.5m,
                            Price = 141.92m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 375.5m,
                            Total = 1303.2m,
                            WaveAndTidal = 1156.0m,
                            Wind2 = 1828.8m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 36,
                            Hydro = 106.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 74.7m,
                            OtherBioEnergy = 1052.8m,
                            Price = 66.92m,
                            Region = "Scotland",
                            SolarPv = 1257.1m,
                            Total = 592.4m,
                            WaveAndTidal = 445.8m,
                            Wind2 = 239.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 37,
                            Hydro = 498.3m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 12.6m,
                            OtherBioEnergy = 320.8m,
                            Price = 13.35m,
                            Region = "Northern Ireland",
                            SolarPv = 924.7m,
                            Total = 343.9m,
                            WaveAndTidal = 520.2m,
                            Wind2 = 608.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 38,
                            Hydro = 801.6m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1470.7m,
                            OtherBioEnergy = 76.9m,
                            Price = 180.88m,
                            Region = "England",
                            SolarPv = 489.0m,
                            Total = 1732.9m,
                            WaveAndTidal = 637.0m,
                            Wind2 = 200.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 39,
                            Hydro = 374.6m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 150.8m,
                            OtherBioEnergy = 517.9m,
                            Price = 88.85m,
                            Region = "England",
                            SolarPv = 1818.2m,
                            Total = 487.1m,
                            WaveAndTidal = 1417.9m,
                            Wind2 = 122.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 40,
                            Hydro = 591.1m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 469.1m,
                            OtherBioEnergy = 1308.6m,
                            Price = 5.56m,
                            Region = "England",
                            SolarPv = 1993.8m,
                            Total = 231.2m,
                            WaveAndTidal = 694.1m,
                            Wind2 = 1492.3m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 41,
                            Hydro = 1856.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1796.0m,
                            OtherBioEnergy = 1601.9m,
                            Price = 187.72m,
                            Region = "England",
                            SolarPv = 1789.0m,
                            Total = 1956.8m,
                            WaveAndTidal = 1494.4m,
                            Wind2 = 240.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 42,
                            Hydro = 1258.2m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 393.8m,
                            OtherBioEnergy = 1190.7m,
                            Price = 45.54m,
                            Region = "Scotland",
                            SolarPv = 163.8m,
                            Total = 701.9m,
                            WaveAndTidal = 1703.9m,
                            Wind2 = 1319.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 43,
                            Hydro = 778.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 766.1m,
                            OtherBioEnergy = 1506.3m,
                            Price = 55.01m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 908.6m,
                            Total = 643.2m,
                            WaveAndTidal = 288.3m,
                            Wind2 = 1833.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 44,
                            Hydro = 1860.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1926.6m,
                            OtherBioEnergy = 627.5m,
                            Price = 189.78m,
                            Region = "England",
                            SolarPv = 1790.1m,
                            Total = 1628.9m,
                            WaveAndTidal = 1855.7m,
                            Wind2 = 1845.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 45,
                            Hydro = 902.4m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 781.9m,
                            OtherBioEnergy = 1788.3m,
                            Price = 196.17m,
                            Region = "Northern Ireland",
                            SolarPv = 1420.4m,
                            Total = 530.3m,
                            WaveAndTidal = 31.6m,
                            Wind2 = 561.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 46,
                            Hydro = 1603.6m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 275.9m,
                            OtherBioEnergy = 1952.3m,
                            Price = 73.56m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1529.8m,
                            Total = 585.7m,
                            WaveAndTidal = 1681.1m,
                            Wind2 = 606.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 47,
                            Hydro = 473.0m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 152.0m,
                            OtherBioEnergy = 1464.1m,
                            Price = 101.05m,
                            Region = "England",
                            SolarPv = 122.9m,
                            Total = 1913.7m,
                            WaveAndTidal = 58.9m,
                            Wind2 = 958.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 48,
                            Hydro = 1798.5m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 933.6m,
                            OtherBioEnergy = 1802.0m,
                            Price = 30.38m,
                            Region = "Scotland",
                            SolarPv = 1971.6m,
                            Total = 867.8m,
                            WaveAndTidal = 740.2m,
                            Wind2 = 1561.8m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 49,
                            Hydro = 1054.1m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1555.5m,
                            OtherBioEnergy = 164.5m,
                            Price = 0.62m,
                            Region = "Northern Ireland",
                            SolarPv = 1700.6m,
                            Total = 325.8m,
                            WaveAndTidal = 1907.6m,
                            Wind2 = 976.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 50,
                            Hydro = 288.9m,
                            Image = "https://2776-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1590.2m,
                            OtherBioEnergy = 502.1m,
                            Price = 18.65m,
                            Region = "Scotland",
                            SolarPv = 871.3m,
                            Total = 1908.7m,
                            WaveAndTidal = 618.4m,
                            Wind2 = 41.7m,
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
