// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyRecordDbContext))]
    [Migration("20211109061658_InitialEnergyRecord")]
    partial class InitialEnergyRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyRecord", "ENERGY_DATASET");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 384.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1390.7m,
                            OtherBioEnergy = 38.7m,
                            Price = 143.99m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1210.4m,
                            Total = 1837.0m,
                            WaveAndTidal = 106.2m,
                            Wind2 = 427.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 90.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 660.8m,
                            OtherBioEnergy = 1881.9m,
                            Price = 158.52m,
                            Region = "Northern Ireland",
                            SolarPv = 1514.7m,
                            Total = 775.9m,
                            WaveAndTidal = 911.5m,
                            Wind2 = 658.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 213.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 810.5m,
                            OtherBioEnergy = 1779.0m,
                            Price = 90.71m,
                            Region = "Northern Ireland",
                            SolarPv = 383.6m,
                            Total = 740.5m,
                            WaveAndTidal = 73.7m,
                            Wind2 = 82.4m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 1962.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1069.4m,
                            OtherBioEnergy = 1610.5m,
                            Price = 49.99m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 591.5m,
                            Total = 244.3m,
                            WaveAndTidal = 1355.6m,
                            Wind2 = 1626.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 5,
                            Hydro = 907.2m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 455.9m,
                            OtherBioEnergy = 1079.8m,
                            Price = 93.83m,
                            Region = "Scotland",
                            SolarPv = 491.7m,
                            Total = 1483.8m,
                            WaveAndTidal = 1414.1m,
                            Wind2 = 1461.3m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 6,
                            Hydro = 661.6m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 975.9m,
                            OtherBioEnergy = 353.9m,
                            Price = 65.83m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1328.4m,
                            Total = 1722.5m,
                            WaveAndTidal = 170.5m,
                            Wind2 = 292.7m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 7,
                            Hydro = 1128.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1179.1m,
                            OtherBioEnergy = 1302.5m,
                            Price = 99.68m,
                            Region = "Scotland",
                            SolarPv = 1554.2m,
                            Total = 319.9m,
                            WaveAndTidal = 1337.0m,
                            Wind2 = 1298.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            Hydro = 538.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1091.2m,
                            OtherBioEnergy = 668.2m,
                            Price = 155.20m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1224.5m,
                            Total = 1582.0m,
                            WaveAndTidal = 1837.5m,
                            Wind2 = 1637.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 9,
                            Hydro = 611.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 882.6m,
                            OtherBioEnergy = 1456.1m,
                            Price = 147.64m,
                            Region = "Scotland",
                            SolarPv = 635.3m,
                            Total = 27.1m,
                            WaveAndTidal = 82.1m,
                            Wind2 = 295.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 10,
                            Hydro = 70.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 274.7m,
                            OtherBioEnergy = 124.3m,
                            Price = 192.98m,
                            Region = "Northern Ireland",
                            SolarPv = 1363.9m,
                            Total = 1859.9m,
                            WaveAndTidal = 1247.4m,
                            Wind2 = 1888.0m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 11,
                            Hydro = 814.3m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1781.3m,
                            OtherBioEnergy = 455.1m,
                            Price = 136.35m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1637.1m,
                            Total = 946.0m,
                            WaveAndTidal = 1931.8m,
                            Wind2 = 759.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 12,
                            Hydro = 1843.6m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1316.5m,
                            OtherBioEnergy = 1215.9m,
                            Price = 78.99m,
                            Region = "England",
                            SolarPv = 1239.2m,
                            Total = 701.7m,
                            WaveAndTidal = 246.1m,
                            Wind2 = 771.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 13,
                            Hydro = 305.6m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1162.2m,
                            OtherBioEnergy = 390.1m,
                            Price = 94.22m,
                            Region = "Scotland",
                            SolarPv = 565.3m,
                            Total = 473.6m,
                            WaveAndTidal = 390.0m,
                            Wind2 = 1275.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 14,
                            Hydro = 604.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 970.8m,
                            OtherBioEnergy = 363.2m,
                            Price = 115.36m,
                            Region = "Northern Ireland",
                            SolarPv = 1748.3m,
                            Total = 444.9m,
                            WaveAndTidal = 218.4m,
                            Wind2 = 808.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 15,
                            Hydro = 679.0m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1943.5m,
                            OtherBioEnergy = 1641.8m,
                            Price = 182.09m,
                            Region = "England",
                            SolarPv = 359.4m,
                            Total = 8.2m,
                            WaveAndTidal = 1237.2m,
                            Wind2 = 510.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 16,
                            Hydro = 5.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1878.0m,
                            OtherBioEnergy = 369.7m,
                            Price = 152.03m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1118.0m,
                            Total = 1366.5m,
                            WaveAndTidal = 917.7m,
                            Wind2 = 1422.6m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 17,
                            Hydro = 603.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1499.3m,
                            OtherBioEnergy = 553.5m,
                            Price = 133.15m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 526.2m,
                            Total = 497.8m,
                            WaveAndTidal = 1792.4m,
                            Wind2 = 1981.5m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 18,
                            Hydro = 1818.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1212.8m,
                            OtherBioEnergy = 38.1m,
                            Price = 63.50m,
                            Region = "Northern Ireland",
                            SolarPv = 111.6m,
                            Total = 30.6m,
                            WaveAndTidal = 880.7m,
                            Wind2 = 770.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 19,
                            Hydro = 1204.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1544.2m,
                            OtherBioEnergy = 1890.6m,
                            Price = 188.62m,
                            Region = "Scotland",
                            SolarPv = 399.3m,
                            Total = 1100.4m,
                            WaveAndTidal = 953.2m,
                            Wind2 = 381.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 20,
                            Hydro = 1439.4m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 445.8m,
                            OtherBioEnergy = 717.6m,
                            Price = 174.31m,
                            Region = "Northern Ireland",
                            SolarPv = 168.8m,
                            Total = 711.0m,
                            WaveAndTidal = 1113.4m,
                            Wind2 = 996.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 21,
                            Hydro = 1800.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 287.8m,
                            OtherBioEnergy = 541.9m,
                            Price = 175.59m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 647.5m,
                            Total = 806.0m,
                            WaveAndTidal = 1373.1m,
                            Wind2 = 1144.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 22,
                            Hydro = 131.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1009.2m,
                            OtherBioEnergy = 1028.3m,
                            Price = 129.98m,
                            Region = "Scotland",
                            SolarPv = 969.3m,
                            Total = 1393.0m,
                            WaveAndTidal = 1480.2m,
                            Wind2 = 339.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 23,
                            Hydro = 271.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1956.5m,
                            OtherBioEnergy = 1657.5m,
                            Price = 132.12m,
                            Region = "Scotland",
                            SolarPv = 1909.0m,
                            Total = 711.8m,
                            WaveAndTidal = 754.6m,
                            Wind2 = 1453.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 24,
                            Hydro = 972.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 376.3m,
                            OtherBioEnergy = 1008.8m,
                            Price = 67.21m,
                            Region = "England",
                            SolarPv = 706.6m,
                            Total = 305.6m,
                            WaveAndTidal = 274.6m,
                            Wind2 = 1327.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 25,
                            Hydro = 886.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 261.8m,
                            OtherBioEnergy = 1516.4m,
                            Price = 59.83m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 950.8m,
                            Total = 144.1m,
                            WaveAndTidal = 1800.5m,
                            Wind2 = 1084.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 26,
                            Hydro = 1570.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1936.9m,
                            OtherBioEnergy = 389.3m,
                            Price = 3.71m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 696.6m,
                            Total = 1464.1m,
                            WaveAndTidal = 1389.7m,
                            Wind2 = 1324.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Hydro = 297.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 512.8m,
                            OtherBioEnergy = 64.4m,
                            Price = 37.58m,
                            Region = "Northern Ireland",
                            SolarPv = 1927.5m,
                            Total = 773.6m,
                            WaveAndTidal = 133.9m,
                            Wind2 = 1830.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 28,
                            Hydro = 56.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 524.1m,
                            OtherBioEnergy = 1652.5m,
                            Price = 199.71m,
                            Region = "England",
                            SolarPv = 404.1m,
                            Total = 1803.8m,
                            WaveAndTidal = 794.6m,
                            Wind2 = 722.6m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 29,
                            Hydro = 1954.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1170.5m,
                            OtherBioEnergy = 1937.3m,
                            Price = 102.28m,
                            Region = "England",
                            SolarPv = 242.0m,
                            Total = 1578.0m,
                            WaveAndTidal = 674.7m,
                            Wind2 = 1513.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 30,
                            Hydro = 286.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1172.2m,
                            OtherBioEnergy = 950.6m,
                            Price = 113.57m,
                            Region = "Scotland",
                            SolarPv = 753.9m,
                            Total = 1872.9m,
                            WaveAndTidal = 1929.8m,
                            Wind2 = 1544.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 31,
                            Hydro = 429.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 694.8m,
                            OtherBioEnergy = 530.0m,
                            Price = 65.36m,
                            Region = "England",
                            SolarPv = 281.6m,
                            Total = 985.5m,
                            WaveAndTidal = 146.9m,
                            Wind2 = 742.8m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 32,
                            Hydro = 1404.3m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1116.9m,
                            OtherBioEnergy = 1155.2m,
                            Price = 63.96m,
                            Region = "England",
                            SolarPv = 366.0m,
                            Total = 1891.8m,
                            WaveAndTidal = 441.2m,
                            Wind2 = 585.5m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 33,
                            Hydro = 1768.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 455.7m,
                            OtherBioEnergy = 792.8m,
                            Price = 197.27m,
                            Region = "Northern Ireland",
                            SolarPv = 961.9m,
                            Total = 40.6m,
                            WaveAndTidal = 1637.8m,
                            Wind2 = 486.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 34,
                            Hydro = 1812.4m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1697.2m,
                            OtherBioEnergy = 1366.3m,
                            Price = 11.73m,
                            Region = "Scotland",
                            SolarPv = 649.5m,
                            Total = 393.0m,
                            WaveAndTidal = 1150.1m,
                            Wind2 = 1779.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 35,
                            Hydro = 750.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1401.4m,
                            OtherBioEnergy = 1103.4m,
                            Price = 181.23m,
                            Region = "Northern Ireland",
                            SolarPv = 89.0m,
                            Total = 1563.7m,
                            WaveAndTidal = 938.3m,
                            Wind2 = 951.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 36,
                            Hydro = 1797.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1710.9m,
                            OtherBioEnergy = 1104.9m,
                            Price = 134.96m,
                            Region = "England",
                            SolarPv = 1527.0m,
                            Total = 1185.0m,
                            WaveAndTidal = 1900.2m,
                            Wind2 = 1058.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 37,
                            Hydro = 1473.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 504.8m,
                            OtherBioEnergy = 1435.3m,
                            Price = 51.31m,
                            Region = "Scotland",
                            SolarPv = 1754.9m,
                            Total = 1791.7m,
                            WaveAndTidal = 868.2m,
                            Wind2 = 489.3m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 38,
                            Hydro = 486.1m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1623.7m,
                            OtherBioEnergy = 1548.0m,
                            Price = 55.36m,
                            Region = "Scotland",
                            SolarPv = 712.8m,
                            Total = 1548.7m,
                            WaveAndTidal = 79.5m,
                            Wind2 = 762.2m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 39,
                            Hydro = 867.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 514.7m,
                            OtherBioEnergy = 1879.2m,
                            Price = 21.10m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 947.5m,
                            Total = 1623.1m,
                            WaveAndTidal = 691.0m,
                            Wind2 = 1229.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 40,
                            Hydro = 1357.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 151.1m,
                            OtherBioEnergy = 83.5m,
                            Price = 85.17m,
                            Region = "Northern Ireland",
                            SolarPv = 1838.3m,
                            Total = 1183.4m,
                            WaveAndTidal = 1879.9m,
                            Wind2 = 181.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 41,
                            Hydro = 1419.2m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1254.7m,
                            OtherBioEnergy = 979.2m,
                            Price = 61.59m,
                            Region = "Scotland",
                            SolarPv = 1642.5m,
                            Total = 1187.4m,
                            WaveAndTidal = 1010.1m,
                            Wind2 = 1311.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 42,
                            Hydro = 621.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 673.0m,
                            OtherBioEnergy = 1798.2m,
                            Price = 104.09m,
                            Region = "England",
                            SolarPv = 146.1m,
                            Total = 1920.6m,
                            WaveAndTidal = 974.0m,
                            Wind2 = 1556.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 43,
                            Hydro = 1114.7m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1569.2m,
                            OtherBioEnergy = 882.3m,
                            Price = 88.72m,
                            Region = "Northern Ireland",
                            SolarPv = 452.1m,
                            Total = 241.1m,
                            WaveAndTidal = 939.9m,
                            Wind2 = 1812.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 44,
                            Hydro = 400.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 40.6m,
                            OtherBioEnergy = 218.9m,
                            Price = 135.49m,
                            Region = "Scotland",
                            SolarPv = 1965.0m,
                            Total = 1048.4m,
                            WaveAndTidal = 932.8m,
                            Wind2 = 364.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 45,
                            Hydro = 1938.5m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1036.0m,
                            OtherBioEnergy = 1207.2m,
                            Price = 152.82m,
                            Region = "Scotland",
                            SolarPv = 677.6m,
                            Total = 1733.8m,
                            WaveAndTidal = 582.2m,
                            Wind2 = 691.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 46,
                            Hydro = 1620.4m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 153.9m,
                            OtherBioEnergy = 371.7m,
                            Price = 121.68m,
                            Region = "England",
                            SolarPv = 1657.5m,
                            Total = 557.9m,
                            WaveAndTidal = 296.1m,
                            Wind2 = 162.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 47,
                            Hydro = 633.9m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1798.2m,
                            OtherBioEnergy = 623.3m,
                            Price = 52.78m,
                            Region = "England",
                            SolarPv = 705.9m,
                            Total = 1008.9m,
                            WaveAndTidal = 1832.4m,
                            Wind2 = 738.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 48,
                            Hydro = 1422.8m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1933.7m,
                            OtherBioEnergy = 1229.9m,
                            Price = 174.51m,
                            Region = "England",
                            SolarPv = 1274.3m,
                            Total = 262.3m,
                            WaveAndTidal = 392.4m,
                            Wind2 = 749.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 49,
                            Hydro = 1982.0m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 1377.3m,
                            OtherBioEnergy = 68.5m,
                            Price = 51.36m,
                            Region = "England",
                            SolarPv = 670.1m,
                            Total = 1275.3m,
                            WaveAndTidal = 1024.3m,
                            Wind2 = 1148.4m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 50,
                            Hydro = 1240.4m,
                            Image = "https://localhost:5001/images/energy.jpeg",
                            LandfillGas = 797.4m,
                            OtherBioEnergy = 859.4m,
                            Price = 34.46m,
                            Region = "Scotland",
                            SolarPv = 1678.1m,
                            Total = 1876.2m,
                            WaveAndTidal = 520.6m,
                            Wind2 = 1661.0m,
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
