// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyGenerationDbContext))]
    [Migration("20211104145806_AddPriceToEnergyGenerations")]
    partial class AddPriceToEnergyGenerations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyGeneration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 1157.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 508.2m,
                            OtherBioEnergy = 1006.0m,
                            Price = 106.29m,
                            Region = "Scotland",
                            SolarPv = 352.9m,
                            Total = 286.7m,
                            WaveAndTidal = 1315.3m,
                            Wind2 = 1434.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 1245.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1086.0m,
                            OtherBioEnergy = 55.4m,
                            Price = 22.53m,
                            Region = "England",
                            SolarPv = 850.5m,
                            Total = 606.6m,
                            WaveAndTidal = 684.7m,
                            Wind2 = 1264.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 1422.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 973.6m,
                            OtherBioEnergy = 991.4m,
                            Price = 132.95m,
                            Region = "Northern Ireland",
                            SolarPv = 1098.3m,
                            Total = 1727.3m,
                            WaveAndTidal = 1510.1m,
                            Wind2 = 469.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 1261.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 238.0m,
                            OtherBioEnergy = 1830.3m,
                            Price = 173.06m,
                            Region = "England",
                            SolarPv = 38.8m,
                            Total = 352.2m,
                            WaveAndTidal = 752.5m,
                            Wind2 = 148.9m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 5,
                            Hydro = 1675.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1523.7m,
                            OtherBioEnergy = 290.8m,
                            Price = 133.13m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1706.4m,
                            Total = 390.0m,
                            WaveAndTidal = 392.8m,
                            Wind2 = 1423.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Hydro = 1711.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1526.9m,
                            OtherBioEnergy = 1924.1m,
                            Price = 77.20m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 783.6m,
                            Total = 216.9m,
                            WaveAndTidal = 1431.1m,
                            Wind2 = 1689.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 7,
                            Hydro = 996.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 301.4m,
                            OtherBioEnergy = 512.1m,
                            Price = 93.00m,
                            Region = "Scotland",
                            SolarPv = 975.8m,
                            Total = 645.9m,
                            WaveAndTidal = 556.1m,
                            Wind2 = 1278.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 8,
                            Hydro = 973.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1170.4m,
                            OtherBioEnergy = 76.8m,
                            Price = 158.88m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1259.0m,
                            Total = 1803.6m,
                            WaveAndTidal = 1275.2m,
                            Wind2 = 1703.2m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 9,
                            Hydro = 71.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 708.2m,
                            OtherBioEnergy = 717.7m,
                            Price = 142.30m,
                            Region = "Northern Ireland",
                            SolarPv = 812.0m,
                            Total = 1968.8m,
                            WaveAndTidal = 955.2m,
                            Wind2 = 601.3m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 10,
                            Hydro = 553.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 27.4m,
                            OtherBioEnergy = 867.2m,
                            Price = 32.75m,
                            Region = "England",
                            SolarPv = 1147.7m,
                            Total = 1417.0m,
                            WaveAndTidal = 1422.1m,
                            Wind2 = 1613.4m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 11,
                            Hydro = 1662.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1474.3m,
                            OtherBioEnergy = 414.0m,
                            Price = 71.03m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1764.9m,
                            Total = 172.1m,
                            WaveAndTidal = 801.1m,
                            Wind2 = 1644.8m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 12,
                            Hydro = 1500.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 915.4m,
                            OtherBioEnergy = 323.3m,
                            Price = 181.04m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1030.9m,
                            Total = 1744.0m,
                            WaveAndTidal = 793.9m,
                            Wind2 = 120.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 13,
                            Hydro = 693.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1642.2m,
                            OtherBioEnergy = 281.1m,
                            Price = 90.38m,
                            Region = "Scotland",
                            SolarPv = 1854.1m,
                            Total = 127.5m,
                            WaveAndTidal = 318.3m,
                            Wind2 = 543.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 14,
                            Hydro = 887.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1037.9m,
                            OtherBioEnergy = 1800.2m,
                            Price = 70.53m,
                            Region = "England",
                            SolarPv = 49.1m,
                            Total = 1190.3m,
                            WaveAndTidal = 1093.2m,
                            Wind2 = 659.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 15,
                            Hydro = 284.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 193.3m,
                            OtherBioEnergy = 819.4m,
                            Price = 114.91m,
                            Region = "England",
                            SolarPv = 1786.6m,
                            Total = 391.2m,
                            WaveAndTidal = 158.4m,
                            Wind2 = 545.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 16,
                            Hydro = 1790.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 468.4m,
                            OtherBioEnergy = 1326.5m,
                            Price = 164.70m,
                            Region = "Scotland",
                            SolarPv = 422.5m,
                            Total = 946.9m,
                            WaveAndTidal = 513.1m,
                            Wind2 = 1123.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 17,
                            Hydro = 237.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 790.2m,
                            OtherBioEnergy = 1027.3m,
                            Price = 107.16m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 864.7m,
                            Total = 744.7m,
                            WaveAndTidal = 1466.7m,
                            Wind2 = 286.4m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 18,
                            Hydro = 1993.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1038.0m,
                            OtherBioEnergy = 384.7m,
                            Price = 14.35m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 306.2m,
                            Total = 531.7m,
                            WaveAndTidal = 594.8m,
                            Wind2 = 1132.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 19,
                            Hydro = 1241.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1180.0m,
                            OtherBioEnergy = 146.6m,
                            Price = 156.95m,
                            Region = "Northern Ireland",
                            SolarPv = 1067.1m,
                            Total = 670.7m,
                            WaveAndTidal = 480.5m,
                            Wind2 = 1889.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 20,
                            Hydro = 1404.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 7.7m,
                            OtherBioEnergy = 1078.8m,
                            Price = 25.89m,
                            Region = "Scotland",
                            SolarPv = 1128.6m,
                            Total = 1293.6m,
                            WaveAndTidal = 118.7m,
                            Wind2 = 853.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 21,
                            Hydro = 523.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 571.1m,
                            OtherBioEnergy = 528.3m,
                            Price = 154.89m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1184.1m,
                            Total = 206.9m,
                            WaveAndTidal = 247.7m,
                            Wind2 = 74.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 22,
                            Hydro = 1197.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1303.2m,
                            OtherBioEnergy = 1805.9m,
                            Price = 42.89m,
                            Region = "England",
                            SolarPv = 571.5m,
                            Total = 399.6m,
                            WaveAndTidal = 1377.4m,
                            Wind2 = 794.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 23,
                            Hydro = 751.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 261.8m,
                            OtherBioEnergy = 1014.1m,
                            Price = 162.31m,
                            Region = "Northern Ireland",
                            SolarPv = 1724.5m,
                            Total = 1466.2m,
                            WaveAndTidal = 485.8m,
                            Wind2 = 356.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 24,
                            Hydro = 1334.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 748.0m,
                            OtherBioEnergy = 1642.2m,
                            Price = 90.17m,
                            Region = "Scotland",
                            SolarPv = 75.2m,
                            Total = 1296.3m,
                            WaveAndTidal = 982.7m,
                            Wind2 = 1091.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 25,
                            Hydro = 335.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 916.6m,
                            OtherBioEnergy = 1475.8m,
                            Price = 54.40m,
                            Region = "Northern Ireland",
                            SolarPv = 1506.7m,
                            Total = 1547.1m,
                            WaveAndTidal = 241.7m,
                            Wind2 = 1939.6m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 26,
                            Hydro = 850.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 809.3m,
                            OtherBioEnergy = 1588.8m,
                            Price = 193.08m,
                            Region = "England",
                            SolarPv = 491.3m,
                            Total = 523.1m,
                            WaveAndTidal = 1670.5m,
                            Wind2 = 679.1m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Hydro = 792.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 992.5m,
                            OtherBioEnergy = 1811.9m,
                            Price = 43.28m,
                            Region = "Scotland",
                            SolarPv = 443.1m,
                            Total = 1302.1m,
                            WaveAndTidal = 1305.2m,
                            Wind2 = 1062.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 28,
                            Hydro = 405.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 704.0m,
                            OtherBioEnergy = 114.8m,
                            Price = 123.75m,
                            Region = "Scotland",
                            SolarPv = 952.7m,
                            Total = 979.0m,
                            WaveAndTidal = 1855.6m,
                            Wind2 = 509.6m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 29,
                            Hydro = 1784.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1280.1m,
                            OtherBioEnergy = 1420.6m,
                            Price = 138.92m,
                            Region = "Northern Ireland",
                            SolarPv = 800.5m,
                            Total = 491.4m,
                            WaveAndTidal = 1535.3m,
                            Wind2 = 1466.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 30,
                            Hydro = 1113.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1589.6m,
                            OtherBioEnergy = 634.4m,
                            Price = 122.45m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 282.8m,
                            Total = 1798.6m,
                            WaveAndTidal = 863.5m,
                            Wind2 = 1119.0m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 31,
                            Hydro = 440.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1692.1m,
                            OtherBioEnergy = 823.4m,
                            Price = 71.39m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1481.1m,
                            Total = 717.7m,
                            WaveAndTidal = 309.6m,
                            Wind2 = 173.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 32,
                            Hydro = 1475.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 90.0m,
                            OtherBioEnergy = 1526.7m,
                            Price = 8.53m,
                            Region = "Northern Ireland",
                            SolarPv = 598.1m,
                            Total = 504.6m,
                            WaveAndTidal = 1133.9m,
                            Wind2 = 609.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 33,
                            Hydro = 1290.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 542.0m,
                            OtherBioEnergy = 1646.1m,
                            Price = 65.91m,
                            Region = "Scotland",
                            SolarPv = 712.9m,
                            Total = 1572.8m,
                            WaveAndTidal = 77.5m,
                            Wind2 = 1320.4m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 34,
                            Hydro = 729.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 612.3m,
                            OtherBioEnergy = 1157.3m,
                            Price = 183.92m,
                            Region = "England",
                            SolarPv = 46.4m,
                            Total = 54.1m,
                            WaveAndTidal = 265.1m,
                            Wind2 = 316.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 35,
                            Hydro = 1830.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 549.4m,
                            OtherBioEnergy = 1985.0m,
                            Price = 36.04m,
                            Region = "England",
                            SolarPv = 1077.9m,
                            Total = 265.4m,
                            WaveAndTidal = 406.0m,
                            Wind2 = 702.8m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 36,
                            Hydro = 1770.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1784.2m,
                            OtherBioEnergy = 96.0m,
                            Price = 80.76m,
                            Region = "England",
                            SolarPv = 1201.1m,
                            Total = 1596.6m,
                            WaveAndTidal = 1139.4m,
                            Wind2 = 129.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 37,
                            Hydro = 77.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 378.2m,
                            OtherBioEnergy = 344.6m,
                            Price = 19.07m,
                            Region = "England",
                            SolarPv = 1269.1m,
                            Total = 1087.5m,
                            WaveAndTidal = 878.4m,
                            Wind2 = 1250.5m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 38,
                            Hydro = 1056.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 869.0m,
                            OtherBioEnergy = 914.4m,
                            Price = 186.81m,
                            Region = "Northern Ireland",
                            SolarPv = 567.2m,
                            Total = 999.6m,
                            WaveAndTidal = 144.2m,
                            Wind2 = 1472.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 39,
                            Hydro = 753.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1939.7m,
                            OtherBioEnergy = 1176.7m,
                            Price = 88.28m,
                            Region = "Northern Ireland",
                            SolarPv = 815.8m,
                            Total = 1063.9m,
                            WaveAndTidal = 765.1m,
                            Wind2 = 1380.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 40,
                            Hydro = 45.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1206.1m,
                            OtherBioEnergy = 1824.3m,
                            Price = 27.56m,
                            Region = "Northern Ireland",
                            SolarPv = 462.3m,
                            Total = 1136.9m,
                            WaveAndTidal = 1863.4m,
                            Wind2 = 1560.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 41,
                            Hydro = 90.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 590.4m,
                            OtherBioEnergy = 1985.5m,
                            Price = 100.08m,
                            Region = "England",
                            SolarPv = 1944.9m,
                            Total = 572.2m,
                            WaveAndTidal = 397.2m,
                            Wind2 = 897.5m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 42,
                            Hydro = 1341.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 665.2m,
                            OtherBioEnergy = 485.4m,
                            Price = 14.51m,
                            Region = "Northern Ireland",
                            SolarPv = 1449.7m,
                            Total = 62.6m,
                            WaveAndTidal = 713.7m,
                            Wind2 = 1096.4m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 43,
                            Hydro = 346.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1371.8m,
                            OtherBioEnergy = 1609.0m,
                            Price = 51.57m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 922.3m,
                            Total = 1681.8m,
                            WaveAndTidal = 811.8m,
                            Wind2 = 1280.7m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 44,
                            Hydro = 536.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1659.4m,
                            OtherBioEnergy = 983.4m,
                            Price = 52.13m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1431.0m,
                            Total = 820.2m,
                            WaveAndTidal = 1998.7m,
                            Wind2 = 1777.4m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 45,
                            Hydro = 75.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1419.8m,
                            OtherBioEnergy = 846.9m,
                            Price = 72.50m,
                            Region = "Scotland",
                            SolarPv = 1373.8m,
                            Total = 413.7m,
                            WaveAndTidal = 918.7m,
                            Wind2 = 604.5m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 46,
                            Hydro = 250.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 924.0m,
                            OtherBioEnergy = 85.6m,
                            Price = 112.12m,
                            Region = "Northern Ireland",
                            SolarPv = 863.6m,
                            Total = 1474.8m,
                            WaveAndTidal = 621.1m,
                            Wind2 = 1761.7m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 47,
                            Hydro = 1857.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1092.3m,
                            OtherBioEnergy = 1097.6m,
                            Price = 159.84m,
                            Region = "Northern Ireland",
                            SolarPv = 295.2m,
                            Total = 1282.7m,
                            WaveAndTidal = 50.8m,
                            Wind2 = 303.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 48,
                            Hydro = 183.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 597.0m,
                            OtherBioEnergy = 361.9m,
                            Price = 91.34m,
                            Region = "Scotland",
                            SolarPv = 352.8m,
                            Total = 1437.9m,
                            WaveAndTidal = 1337.5m,
                            Wind2 = 1665.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 49,
                            Hydro = 1129.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1282.9m,
                            OtherBioEnergy = 1156.2m,
                            Price = 84.64m,
                            Region = "Northern Ireland",
                            SolarPv = 1140.7m,
                            Total = 1135.1m,
                            WaveAndTidal = 560.5m,
                            Wind2 = 1195.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 50,
                            Hydro = 1181.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1650.4m,
                            OtherBioEnergy = 553.6m,
                            Price = 118.07m,
                            Region = "Scotland",
                            SolarPv = 6.1m,
                            Total = 623.5m,
                            WaveAndTidal = 1221.8m,
                            Wind2 = 1508.5m,
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
