// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyGenerationDbContext))]
    [Migration("20211104144139_UpdateEnergyGenerations")]
    partial class UpdateEnergyGenerations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyGeneration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 1530.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1677.4m,
                            OtherBioEnergy = 76.9m,
                            Region = "Northern Ireland",
                            SolarPv = 1517.3m,
                            Total = 563.7m,
                            WaveAndTidal = 800.0m,
                            Wind2 = 221.3m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 860.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 447.8m,
                            OtherBioEnergy = 1788.3m,
                            Region = "Northern Ireland",
                            SolarPv = 110.1m,
                            Total = 1397.1m,
                            WaveAndTidal = 233.3m,
                            Wind2 = 994.0m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 887.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1855.1m,
                            OtherBioEnergy = 1081.3m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1136.9m,
                            Total = 671.8m,
                            WaveAndTidal = 225.6m,
                            Wind2 = 197.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 185.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1327.8m,
                            OtherBioEnergy = 1834.0m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 300.2m,
                            Total = 416.2m,
                            WaveAndTidal = 447.9m,
                            Wind2 = 763.5m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 5,
                            Hydro = 1944.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 670.1m,
                            OtherBioEnergy = 751.4m,
                            Region = "Northern Ireland",
                            SolarPv = 1847.7m,
                            Total = 339.0m,
                            WaveAndTidal = 1112.1m,
                            Wind2 = 236.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 6,
                            Hydro = 1935.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1466.3m,
                            OtherBioEnergy = 159.8m,
                            Region = "Scotland",
                            SolarPv = 45.2m,
                            Total = 27.2m,
                            WaveAndTidal = 252.5m,
                            Wind2 = 224.3m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 7,
                            Hydro = 435.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 859.0m,
                            OtherBioEnergy = 1275.3m,
                            Region = "Northern Ireland",
                            SolarPv = 944.8m,
                            Total = 894.3m,
                            WaveAndTidal = 1333.6m,
                            Wind2 = 1542.0m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 8,
                            Hydro = 276.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 444.0m,
                            OtherBioEnergy = 1016.6m,
                            Region = "Northern Ireland",
                            SolarPv = 905.4m,
                            Total = 1051.7m,
                            WaveAndTidal = 808.6m,
                            Wind2 = 262.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 9,
                            Hydro = 385.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 548.5m,
                            OtherBioEnergy = 501.8m,
                            Region = "England",
                            SolarPv = 1555.4m,
                            Total = 1242.8m,
                            WaveAndTidal = 253.4m,
                            Wind2 = 1480.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 10,
                            Hydro = 140.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 158.1m,
                            OtherBioEnergy = 634.9m,
                            Region = "England",
                            SolarPv = 981.6m,
                            Total = 1255.3m,
                            WaveAndTidal = 828.4m,
                            Wind2 = 1137.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 11,
                            Hydro = 572.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1049.8m,
                            OtherBioEnergy = 869.9m,
                            Region = "England",
                            SolarPv = 253.1m,
                            Total = 1794.9m,
                            WaveAndTidal = 1800.4m,
                            Wind2 = 1791.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 12,
                            Hydro = 1028.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 883.4m,
                            OtherBioEnergy = 305.5m,
                            Region = "Northern Ireland",
                            SolarPv = 1808.5m,
                            Total = 1830.3m,
                            WaveAndTidal = 1948.1m,
                            Wind2 = 932.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 13,
                            Hydro = 442.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1193.0m,
                            OtherBioEnergy = 411.5m,
                            Region = "England",
                            SolarPv = 785.0m,
                            Total = 1125.7m,
                            WaveAndTidal = 1156.6m,
                            Wind2 = 1023.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 14,
                            Hydro = 270.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1020.7m,
                            OtherBioEnergy = 1569.9m,
                            Region = "Northern Ireland",
                            SolarPv = 650.5m,
                            Total = 919.0m,
                            WaveAndTidal = 122.3m,
                            Wind2 = 1974.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 15,
                            Hydro = 685.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 590.4m,
                            OtherBioEnergy = 472.3m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1203.5m,
                            Total = 1957.2m,
                            WaveAndTidal = 908.0m,
                            Wind2 = 76.2m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 16,
                            Hydro = 676.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 310.0m,
                            OtherBioEnergy = 1611.3m,
                            Region = "England",
                            SolarPv = 1945.0m,
                            Total = 195.3m,
                            WaveAndTidal = 108.7m,
                            Wind2 = 341.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 17,
                            Hydro = 1841.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1446.6m,
                            OtherBioEnergy = 1292.7m,
                            Region = "Scotland",
                            SolarPv = 607.4m,
                            Total = 1898.2m,
                            WaveAndTidal = 1348.7m,
                            Wind2 = 1312.5m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 18,
                            Hydro = 238.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 109.4m,
                            OtherBioEnergy = 1623.4m,
                            Region = "Scotland",
                            SolarPv = 927.3m,
                            Total = 945.3m,
                            WaveAndTidal = 662.4m,
                            Wind2 = 1894.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 19,
                            Hydro = 312.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 485.7m,
                            OtherBioEnergy = 883.1m,
                            Region = "Scotland",
                            SolarPv = 566.1m,
                            Total = 1912.2m,
                            WaveAndTidal = 337.7m,
                            Wind2 = 1235.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 20,
                            Hydro = 1039.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 75.2m,
                            OtherBioEnergy = 788.6m,
                            Region = "Scotland",
                            SolarPv = 1812.3m,
                            Total = 1852.4m,
                            WaveAndTidal = 1298.8m,
                            Wind2 = 1026.7m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 21,
                            Hydro = 1910.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 787.2m,
                            OtherBioEnergy = 770.4m,
                            Region = "Scotland",
                            SolarPv = 1461.4m,
                            Total = 518.3m,
                            WaveAndTidal = 234.6m,
                            Wind2 = 752.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 22,
                            Hydro = 321.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1730.7m,
                            OtherBioEnergy = 555.9m,
                            Region = "Scotland",
                            SolarPv = 1999.2m,
                            Total = 1972.5m,
                            WaveAndTidal = 102.3m,
                            Wind2 = 1571.8m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 23,
                            Hydro = 1724.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1929.3m,
                            OtherBioEnergy = 661.8m,
                            Region = "Scotland",
                            SolarPv = 863.0m,
                            Total = 1644.4m,
                            WaveAndTidal = 999.8m,
                            Wind2 = 1151.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 24,
                            Hydro = 138.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 386.1m,
                            OtherBioEnergy = 502.9m,
                            Region = "Northern Ireland",
                            SolarPv = 587.2m,
                            Total = 1712.3m,
                            WaveAndTidal = 854.9m,
                            Wind2 = 141.5m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 25,
                            Hydro = 1795.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1794.3m,
                            OtherBioEnergy = 422.6m,
                            Region = "Scotland",
                            SolarPv = 1550.4m,
                            Total = 1235.6m,
                            WaveAndTidal = 1325.1m,
                            Wind2 = 177.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 26,
                            Hydro = 1256.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1066.5m,
                            OtherBioEnergy = 1115.7m,
                            Region = "Northern Ireland",
                            SolarPv = 1568.1m,
                            Total = 894.1m,
                            WaveAndTidal = 705.1m,
                            Wind2 = 1649.0m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Hydro = 799.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 266.3m,
                            OtherBioEnergy = 1915.7m,
                            Region = "Northern Ireland",
                            SolarPv = 305.2m,
                            Total = 249.2m,
                            WaveAndTidal = 1028.5m,
                            Wind2 = 1048.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 28,
                            Hydro = 1496.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 609.2m,
                            OtherBioEnergy = 1538.2m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1716.1m,
                            Total = 1036.5m,
                            WaveAndTidal = 1433.1m,
                            Wind2 = 1060.3m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 29,
                            Hydro = 440.3m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 488.6m,
                            OtherBioEnergy = 1589.0m,
                            Region = "Scotland",
                            SolarPv = 1205.4m,
                            Total = 1979.4m,
                            WaveAndTidal = 1355.5m,
                            Wind2 = 343.9m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 30,
                            Hydro = 1471.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1244.5m,
                            OtherBioEnergy = 1685.0m,
                            Region = "England",
                            SolarPv = 1788.4m,
                            Total = 1896.1m,
                            WaveAndTidal = 885.2m,
                            Wind2 = 953.0m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 31,
                            Hydro = 1634.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1546.5m,
                            OtherBioEnergy = 1417.5m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1058.7m,
                            Total = 1214.5m,
                            WaveAndTidal = 1377.7m,
                            Wind2 = 1214.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 32,
                            Hydro = 29.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 219.8m,
                            OtherBioEnergy = 1271.2m,
                            Region = "Northern Ireland",
                            SolarPv = 95.8m,
                            Total = 1481.4m,
                            WaveAndTidal = 152.7m,
                            Wind2 = 966.1m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 33,
                            Hydro = 716.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 820.0m,
                            OtherBioEnergy = 270.9m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 539.9m,
                            Total = 1749.4m,
                            WaveAndTidal = 607.8m,
                            Wind2 = 1401.2m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 34,
                            Hydro = 31.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1600.1m,
                            OtherBioEnergy = 1945.1m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 188.5m,
                            Total = 374.3m,
                            WaveAndTidal = 1588.8m,
                            Wind2 = 1419.6m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 35,
                            Hydro = 1787.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1225.7m,
                            OtherBioEnergy = 313.3m,
                            Region = "England",
                            SolarPv = 1808.9m,
                            Total = 681.7m,
                            WaveAndTidal = 709.2m,
                            Wind2 = 575.5m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 36,
                            Hydro = 517.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1989.9m,
                            OtherBioEnergy = 694.4m,
                            Region = "Scotland",
                            SolarPv = 665.3m,
                            Total = 339.4m,
                            WaveAndTidal = 923.1m,
                            Wind2 = 70.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 37,
                            Hydro = 787.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1885.2m,
                            OtherBioEnergy = 250.3m,
                            Region = "England",
                            SolarPv = 557.6m,
                            Total = 1925.9m,
                            WaveAndTidal = 497.9m,
                            Wind2 = 623.9m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 38,
                            Hydro = 150.7m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1655.5m,
                            OtherBioEnergy = 397.5m,
                            Region = "Northern Ireland",
                            SolarPv = 552.5m,
                            Total = 853.7m,
                            WaveAndTidal = 935.0m,
                            Wind2 = 718.7m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 39,
                            Hydro = 226.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 34.4m,
                            OtherBioEnergy = 1806.7m,
                            Region = "Scotland",
                            SolarPv = 1382.1m,
                            Total = 428.2m,
                            WaveAndTidal = 1613.3m,
                            Wind2 = 1536.6m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 40,
                            Hydro = 1494.1m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1691.6m,
                            OtherBioEnergy = 1105.2m,
                            Region = "England",
                            SolarPv = 1598.9m,
                            Total = 1888.7m,
                            WaveAndTidal = 902.5m,
                            Wind2 = 826.2m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 41,
                            Hydro = 1558.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1861.9m,
                            OtherBioEnergy = 1430.8m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 823.9m,
                            Total = 1726.8m,
                            WaveAndTidal = 1787.7m,
                            Wind2 = 1859.8m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 42,
                            Hydro = 267.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1663.3m,
                            OtherBioEnergy = 1083.9m,
                            Region = "England",
                            SolarPv = 1267.6m,
                            Total = 853.4m,
                            WaveAndTidal = 1919.7m,
                            Wind2 = 1290.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 43,
                            Hydro = 750.8m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 359.4m,
                            OtherBioEnergy = 206.3m,
                            Region = "Northern Ireland",
                            SolarPv = 463.4m,
                            Total = 1877.2m,
                            WaveAndTidal = 397.3m,
                            Wind2 = 674.1m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 44,
                            Hydro = 1447.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 261.9m,
                            OtherBioEnergy = 1905.0m,
                            Region = "Northern Ireland",
                            SolarPv = 1243.3m,
                            Total = 1073.1m,
                            WaveAndTidal = 1224.5m,
                            Wind2 = 987.4m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 45,
                            Hydro = 1951.2m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 499.7m,
                            OtherBioEnergy = 71.4m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1751.3m,
                            Total = 1728.5m,
                            WaveAndTidal = 1977.9m,
                            Wind2 = 1016.9m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 46,
                            Hydro = 514.9m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 640.6m,
                            OtherBioEnergy = 888.8m,
                            Region = "Scotland",
                            SolarPv = 1239.2m,
                            Total = 223.7m,
                            WaveAndTidal = 558.3m,
                            Wind2 = 1105.5m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 47,
                            Hydro = 617.6m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1681.4m,
                            OtherBioEnergy = 762.1m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 1428.3m,
                            Total = 538.4m,
                            WaveAndTidal = 1108.9m,
                            Wind2 = 860.9m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 48,
                            Hydro = 1362.5m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1194.7m,
                            OtherBioEnergy = 669.3m,
                            Region = "Northern Ireland",
                            SolarPv = 1657.7m,
                            Total = 1965.8m,
                            WaveAndTidal = 1842.8m,
                            Wind2 = 834.8m,
                            Year = 2004
                        },
                        new
                        {
                            Id = 49,
                            Hydro = 392.0m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1022.3m,
                            OtherBioEnergy = 1221.3m,
                            Region = "Northern Ireland",
                            SolarPv = 1897.5m,
                            Total = 447.1m,
                            WaveAndTidal = 722.8m,
                            Wind2 = 1130.1m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 50,
                            Hydro = 354.4m,
                            Image = "https://24e0-138-75-155-224.ngrok.io/images/energy.jpeg",
                            LandfillGas = 1223.5m,
                            OtherBioEnergy = 1047.3m,
                            Region = "Northern Ireland",
                            SolarPv = 583.9m,
                            Total = 551.8m,
                            WaveAndTidal = 472.5m,
                            Wind2 = 1653.0m,
                            Year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
