// <auto-generated />
using EnergyAPI.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnergyAPI.Migrations
{
    [DbContext(typeof(EnergyGenerationDbContext))]
    partial class EnergyGenerationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnergyAPI.Models.EnergyGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Hydro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("LandfillGas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("OtherBioEnergy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SolarPv")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("WaveAndTidal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("Wind2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 1)
                        .HasColumnType("decimal(14,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyGeneration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hydro = 25.3m,
                            LandfillGas = 2899.0m,
                            OtherBioEnergy = 2716.9m,
                            Region = "England",
                            SolarPv = 25.3m,
                            Total = 5990.4m,
                            WaveAndTidal = 0.0m,
                            Wind2 = 349.2m,
                            Year = 2003
                        },
                        new
                        {
                            Id = 2,
                            Hydro = 30.8m,
                            LandfillGas = 22.5m,
                            OtherBioEnergy = 0.8m,
                            Region = "Northern Ireland",
                            SolarPv = 0.0m,
                            Total = 19.3m,
                            WaveAndTidal = 0.6m,
                            Wind2 = 743.8m,
                            Year = 2009
                        },
                        new
                        {
                            Id = 3,
                            Hydro = 6.5m,
                            LandfillGas = 465.3m,
                            OtherBioEnergy = 31.8m,
                            Region = "Yorkshire and the Humber",
                            SolarPv = 129.6m,
                            Total = 3637.6m,
                            WaveAndTidal = 0.2m,
                            Wind2 = 774.5m,
                            Year = 2013
                        },
                        new
                        {
                            Id = 4,
                            Hydro = 5757.1m,
                            LandfillGas = 503.4m,
                            OtherBioEnergy = 26.2m,
                            Region = "Scotland",
                            SolarPv = 173.9m,
                            Total = 1331.4m,
                            WaveAndTidal = 2.0m,
                            Wind2 = 13833.5m,
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
